/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swim;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static swim.cn.cn;

/**
 *
 * @author tinnakorn
 */
public class paymanagerstudy extends javax.swing.JFrame {

    /**
     * Creates new form staff
     */
    DefaultTableModel model = new DefaultTableModel();
    public paymanagerstudy() {
        
                
        initComponents();
        
         Calendar c = Calendar.getInstance();
		SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
		String currentDate = df.format(c.getTime());
		jLabel5.setText(currentDate);
        
    model.addColumn("ID");
    model.addColumn("ชื่อ USER");
    model.addColumn("ประเภท USER");
    model.addColumn("สถานะ");
      
     try{
        ResultSet rs = cn().executeQuery("Select * from registerstudy");
    while(rs.next()){
        String a = null;
        if(rs.getInt("status")==1){
        a="No Active";
        }
        else if(rs.getInt("status")==2){
        a="Active";
        }
    model.addRow(new Object[]{rs.getString("r_codeid"),rs.getString("r_name_user"),rs.getString("r_type"),a});
    }
    
    }catch(Exception e){System.err.println(e);}
    jTable2.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField3 = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 300));
        getContentPane().setLayout(null);
        getContentPane().add(textField3);
        textField3.setBounds(260, 30, 131, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("รหัสประชาชน/รหัสนักศึกษา");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(46, 30, 204, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("วันที่ชำระ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(730, 80, 69, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("จำนวนเงิน");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(730, 130, 76, 22);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("ชำระ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(810, 190, 120, 30);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(50, 80, 560, 163);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(830, 80, 131, 24);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ข้อมูลสมาชิก");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(460, 50, 100, 22);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "500" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(830, 130, 80, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("บาท");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(920, 130, 34, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swim/img/1457732752_Refresh.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(570, 42, 32, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swim/img/1457737890_logout.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10);
        jLabel10.setBounds(960, 10, 40, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swim/img/pexels-photo.jpeg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1030, 300);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(690, 250, 0, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String codeid1 =(String) jComboBox1.getSelectedItem();
        String date1 = jLabel5.getText();
        String pay1 = textField3.getText();
        if(pay1.length() == 0){
            JOptionPane.showMessageDialog(null,"ทำรายการไม่ถูกต้อง");
            return;
        }
        
        try
     {
      
         Statement stmt = null; 
         cn c = new cn();
         stmt = c.cn();
         String pay =(String) jComboBox1.getSelectedItem();
        String date = jLabel5.getText();
        String codeid = textField3.getText();
        String name =jLabel9.getText();
      String result = "INSERT INTO pay(p_codeuser,p_name,p_datetime,p_money)VALUES('"+codeid+"','"+name+"','"+date+"','"+pay+"')";
      String result2 = "UPDATE registerstudy SET status='2' where r_codeid = '"+codeid+"'";
       stmt.executeUpdate(result);
        stmt.executeUpdate(result2);


JOptionPane.showMessageDialog(null,"บันทึกแล้ว");

     }
     catch(Exception e)
     {
         JOptionPane.showMessageDialog(null, e.getMessage() ,"Error", 1);

     }   
 try{
     model.setRowCount(0);
        ResultSet rs = cn().executeQuery("Select * from registerstudy");
    while(rs.next()){
        String a = null;
        if(rs.getInt("status")==1){
        a="No Active";
        }
        else if(rs.getInt("status")==2){
        a="Active";
        }
    model.addRow(new Object[]{rs.getString("r_codeid"),rs.getString("r_name_user"),rs.getString("r_type"),a});
    }
    
    }catch(Exception e){System.err.println(e);}
    jTable2.setModel(model);        // TODO add your handling code here:
                                           // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
      try{
    int i=jTable2.getSelectedRow();deplace(i);
}
catch (Exception e){JOptionPane.showMessageDialog(null,"error"+e.getLocalizedMessage());}       // TODO add your handling code here:
      // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        
   try{
       model.setRowCount(0);
        ResultSet rs = cn().executeQuery("Select * from registerstudy");
    while(rs.next()){
        String a = null;
        if(rs.getInt("status")==1){
        a="No Active";
        }
        else if(rs.getInt("status")==2){
        a="Active";
        }
    model.addRow(new Object[]{rs.getString("r_codeid"),rs.getString("r_name_user"),rs.getString("r_type"),a});
    }
    
    }catch(Exception e){System.err.println(e);}
    jTable2.setModel(model);       // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
staffmain mm = new staffmain();
mm.setVisible(true);
setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paymanagerstudy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paymanagerstudy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paymanagerstudy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paymanagerstudy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paymanagerstudy().setVisible(true);
            }
            
        });
    }
 private void deplace(int i){
   try{
    textField3.setText(model.getValueAt(i,0).toString());
    jLabel9.setText(model.getValueAt(i,1).toString());
    
    String aa;
    if(model.getValueAt(i,3).toString()=="No Active"){
    jComboBox1.setSelectedItem("500".toString());
    }
    
   // jTextField4.setText(model.getValueAt(i,4).toString());

    }catch (Exception e){System.err.println(e);
    JOptionPane.showMessageDialog(null,"error"+e.getLocalizedMessage());
    }
 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private java.awt.TextField textField3;
    // End of variables declaration//GEN-END:variables
}
